model: codegen-350M-mono
checkpoints_dir: ./checkpoints/
device: cuda
seed: 42
deterministic: False
top_p: 0.95
temp: 0.85
timeout: 5  # Seconds
gpus: 1
max_length: 128
batch_size: 300
n_trials: 1000
n_bugs: 1
fp16: False
pad_token: 50256
tasks: ["parity"]
run_name: ???  # Mandatory string argument that describes the run.

###################################################################################################
# Hydra config overrides:
hydra:
    run:
        dir: logs/${run_name}
    sweep:
        dir: logs/${run_name}
