model: Salesforce/codegen-350M-mono
checkpoints_dir: checkpoints
cuda: True
seed: 42
deterministic: False
top_p: 0.95
temp: 0.8
timeout: 5  # Seconds
gpus: 1
gen_max_len: 512
batch_size: 16
n_trials: 500
n_bugs: 1
fp16: True
debug: False
pad_token: 50256
seeds: ["radial", "wheel", "square"]
run_name: ???  # Mandatory string argument that describes the run.

###################################################################################################
# Hydra config overrides:
hydra:
    run:
        dir: logs/${run_name}
    sweep:
        dir: logs/${run_name}
