model: Salesforce/codegen-350M-mono
save_path: /fsx/home-hyperion/OpenELM/data
cuda: True
seed: 42
deterministic: False
top_p: 0.95
temp: 0.85
timeout: 5  # Seconds
gpus: 1
gen_max_len: 512
batch_size: 16
n_trials: 1000
n_bugs: 1
fp16: True
debug: False
processes: 1
pad_token: 50256
seeds: ["square","radial","cppn_fixed"]
# Instructoin = 0: No instruction
# Instruction = 1: "def make_walker():\n"
# Instruction = 2: "#Create a new walker by modifying the starting function above.\ndef make_walker():\n"
# Instruction = 3: "#Combine the {seed_one}, {seed_two}, {seed_three} starting programs
# above to make a new program\ndef make_walker():\n"
instruction: 1
run_name:  # String argument that describes the run.

###################################################################################################
# Hydra config overrides:
hydra:
    run:
        dir: logs/${run_name}
    sweep:
        dir: logs/${run_name}
