model:
  model_path: "lvwerra/gpt2-imdb"  # Name of hf model to load
  tokenizer_path: "gpt2"  # Name of hf tokenizer to load
  model_type : "AcceleratePPOSoftpromptModel"  # Name of accelerate model type to load
  num_layers_unfrozen: 0  # Number of bottom layers to freeze during training

train:
  seq_length: 48  # Size of LM context
  epochs: 1000  # Train for max(epochs, total_steps)
  total_steps: 10000  # Train for max(epochs, total_steps)
  batch_size: 128  # batch size

  lr_ramp_steps: 100  # learning rate warm up
  lr_decay_steps: 79000  # learning rate decay
  weight_decay: 1.0e-6  # weight decay param
  learning_rate_init: 1.412e-4  # init learning rate
  learning_rate_target: 1.412e-4  # target final learning rate
  opt_betas: [0.9, 0.95] # adam betas

  checkpoint_interval: 10000  # checkpoint interval
  eval_interval: 16  # eval interval

  pipeline: "PPOPipeline"  # prompt pipeline to load
  orchestrator: "PPOOrchestrator"  # orchestrator to load

method:
  name : 'pposoftpromptconfig'  # Name of RL method config
  n_soft_tokens: 1  # Number of (prefix) soft prompt tokens
  initialize_from_vocab: True  # Initialize learned soft prompt embeddings from vocab
  num_rollouts: 128  # Number of rollouts to collect per epoch
  chunk_size: 128  # Number of rollouts to collect in one loop of orchestrator
  ppo_epochs: 4  # Number of ppo epochs
  init_kl_coef: 0.2  # init kl coefficient
  target: 6  # target kl coefficient, set None for fixed kl coef
  horizon: 10000  # PPO horizon
  gamma: 1  # PPO discount
  lam: 0.95  # PPO lambda
  cliprange: 0.2  # clip range
  cliprange_value: 0.2  # clip range
  vf_coef: 2.3  # value term weight
  gen_kwargs:
    max_length: 48  # LM max sample gen length, n_soft_tokens will be added
    min_length: 48  # LM min sample gen length, n_soft_tokens will be added
    top_k: 0.0  # top k
    top_p: 1.0  # top p
    do_sample: True  # sample
